### ISSUE TITLE
Add the possibility to export a file (dot)

### ISSUE THREAD

**Issue by bepolymathe** [Kungsgeten/org-brain-export#8]
Currently, we have two solutions to export in .dot the structure of notes: export the whole "brain" or export an "entry". You can't export a file (created by `org-brain-add-child`) without having to add an entry at the beginning of the file, then to shift all entries one level (to keep the structure). Only then you can apply `org-brain-export-dot-entry` on this new headline. 

Is it possible to consider adding an `org-brain-export-dot-file` option?

**Comment by bepolymathe** [comment]
@Kungsgeten what do you think about this ?

**Comment by Kungsgeten** [comment]
Hi! I haven't used the export since I created it. I haven't found much need for exporting, but its a feature often requested. So I don't think about it much :)

I don't quite understand the suggestion. Can't you just export the file entry?

**Comment by bepolymathe** [comment]
Hi, 

Let's think about it then ;-) 

Currently, either I export the whole brain, or I export one headline. However, I have files that have a thematic consistency and I'd like to visualize the connections. For example, I'm reading something at the moment on the theme of education (article, book, etc). So I have an education.org file. This file contains a hierarchical structuring (e.g. book/chapter/highlights...) but also cross-references between headings (non-hierarchical). I even have links that appear as backlinks to other files. I must even have some edges. 

This structuring finally becomes quite complex with time and it would be very interesting to be able to visualize it. So yes I could create a level 1 header at the top of the file and export but it's a bit annoying for org-brain-visualize afterwards. 

Anyway, this feature is in demand because navigating visually through your notes is very useful for research work (or for students for ex). obvz seems to be interesting for that but I don't know what you think about it...

**Comment by Kungsgeten** [comment]
Ok, but can't you use `org-brain-visualize` on `education` and then press `m` to go into mind map mode and press `z` and/or `+` in order to get the level of ascendants/descendants you want, and finally use `org-brain-export-dot-entry`? How would exporting a file be different?

**Comment by bepolymathe** [comment]
Basically, you're right. I can do it like this. I'm closing this issue because it's a lot of complication for nothing.
